create table if not exists FILME (
    ID int AUTO_INCREMENT PRIMARY KEY,
    VL_ANO INT,
    DS_TITULO VARCHAR(255),
    TP_VENCEDOR CHAR(1)
);

create table if not exists FILME_PRODUTOR (
    ID int AUTO_INCREMENT PRIMARY KEY,
    ID_FILME INT NOT NULL,
    NM_PRODUTOR VARCHAR(255),
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID)
);

create table if not exists FILME_ESTUDIO (
    ID int AUTO_INCREMENT PRIMARY KEY,
    ID_FILME INT NOT NULL,
    NM_ESTUDIO VARCHAR(255),
    FOREIGN KEY (ID_FILME) REFERENCES FILME(ID)
);

create table if not exists FILME_CSV (
    VL_ANO VARCHAR(255),
    DS_TITULO VARCHAR(255),
    DS_ESTUDIO VARCHAR(255),
    DS_PRODUTOR VARCHAR(255),
    DS_VENCEDOR VARCHAR(255)
);